import FWCore.ParameterSet.Config as cms

source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_522_1_KaP.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_174_1_27T.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_635_1_ryr.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_270_1_HHm.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_576_1_oy8.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_660_2_GXt.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_473_1_Rzg.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_808_1_HPg.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_419_1_Bv6.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_860_1_G0r.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_517_1_1TH.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_876_1_pjY.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_910_1_Ca1.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_284_1_CIm.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_488_3_6NQ.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_156_1_DhK.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_729_1_wf1.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_401_1_cv2.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_973_3_0yA.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_519_2_MJd.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_659_1_20t.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_81_1_rA2.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_281_1_QNc.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_943_2_dyS.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_278_1_eXJ.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_937_1_dwZ.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_561_1_YTV.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_658_2_fS4.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_20_1_uJS.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_332_1_DIs.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_758_1_KaY.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_643_1_Mc0.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_237_1_Rpd.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_182_1_Iqt.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_528_1_rw8.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_242_1_aWV.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_100_1_00D.root',
         '/store/user/skaplan/noreplica/MinBias14TeV/outfile14TeVSKIM_804_1_f6b.root',
    )

)
