import FWCore.ParameterSet.Config as cms

source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_104_1_Lix.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_319_1_YSB.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_641_1_l4z.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_477_1_dPm.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_648_1_q3p.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_449_1_4qZ.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_728_1_Q70.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_45_1_FXQ.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_422_1_JIR.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_43_1_hKU.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_14_1_dbL.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_618_1_VBZ.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_510_1_pc8.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_710_1_2tc.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_603_1_Lfn.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_637_1_6p2.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_491_1_txt.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_25_1_tLc.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_472_1_b2R.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_255_1_Gm6.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_561_1_YVe.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_469_1_MAZ.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_671_1_PDs.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_452_1_0jH.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_115_1_puu.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_275_1_dUL.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_343_1_DmY.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_748_1_HcE.root',
         '/store/user/skaplan/noreplica/MinBias_GaussZ/outfile14TeVSKIM_467_1_nia.root',
    )

)
