from ROOT import *


i = TFile("pileuptreePU1.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","recreate")
newtree = tree.CloneTree()
newtree.SetName("tree_PU1")
newtree.Write()
i.Close()
o.Close()

i = TFile("pileuptreePU2.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU2")
newtree.Write()
i.Close()
o.Close()

i = TFile("pileuptreePU3.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU3")
newtree.Write()
i.Close()
o.Close()

i = TFile("pileuptreePU5.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU5")
newtree.Write()
i.Close()
o.Close()

i = TFile("pileuptreePU10.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU10")
newtree.Write()
i.Close()
o.Close()

i = TFile("pileuptreePU15.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU15")
newtree.Write()
i.Close()
o.Close()

i = TFile("pileuptreePU20.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU20")
newtree.Write()
i.Close()
o.Close()


i = TFile("pileuptreePU30.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU30")
newtree.Write()
i.Close()
o.Close()


i = TFile("pileuptreePU40.root","READ")
tree = i.Get("produce/tree")
o = TFile("pileuptrees.root","update")
newtree = tree.CloneTree()
newtree.SetName("tree_PU40")
newtree.Write()
i.Close()
o.Close()
