import FWCore.ParameterSet.Config as cms

source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_128_1_4GC.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_131_1_9t1.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_142_1_u3Q.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_152_1_TNG.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_160_1_yKE.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_185_1_SFG.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_201_1_ZQK.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_209_1_oUC.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_219_1_LVo.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_225_1_HOU.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_242_1_tRf.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_268_1_j7g.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_270_1_mJi.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_296_1_fhW.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_326_1_L3Q.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_338_1_McJ.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_404_1_Zls.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_429_1_wbq.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_441_1_vrJ.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_442_1_vBt.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_456_1_xwG.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_489_1_O73.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_493_1_d2o.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_503_1_2ph.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_534_1_yIT.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_546_1_egp.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_562_1_6gw.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_564_1_sIm.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_568_1_qxd.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_620_1_h6p.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_629_1_E0Z.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_635_1_qin.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_652_1_yKM.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_656_1_WN2.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_731_1_tA9.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_745_1_tFx.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_758_1_F56.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_776_1_Vd8.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_808_1_YHy.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_822_1_XMA.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_824_1_HJ7.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_855_1_6Oc.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_870_1_sAi.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_904_1_pdR.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_912_1_AHX.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_913_1_Tl4.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_925_1_rvJ.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_951_1_vK2.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_978_1_Tew.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_993_1_Oyv.root',
'/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_9_1_a50.root',
    )

)
