import FWCore.ParameterSet.Config as cms

source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_684_1_Gin.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_436_1_ibq.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_226_1_AxF.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_852_1_3mK.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_580_1_EXb.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_771_1_cPl.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_139_1_MHF.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_453_1_EZV.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_850_1_VS7.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_76_1_KnI.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_289_1_vAX.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_844_1_rKq.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_737_1_mUw.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_723_1_Q9I.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_379_1_Hve.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_726_1_0ui.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_405_1_Uwn.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_826_1_mJO.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_202_1_Cab.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_498_1_Ldh.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_952_1_kY8.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_98_1_5rm.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_66_1_y8k.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_281_1_EIM.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_365_1_aTk.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_659_1_54v.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_307_1_9l9.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_262_1_QGY.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_124_1_4DA.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_934_1_LBw.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_648_1_LA0.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_861_1_Jiu.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_415_1_DOP.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_217_1_qx7.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_574_1_vBm.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_579_1_0Y3.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_46_1_pMh.root',
         '/store/user/skaplan/noreplica/MinBias14TeV_NoSmear/outfile14TeVSKIM_435_1_rZ4.root',
    )

)
